notARepository: 'quit'
os:
  editPreset: nvim
gui:
  showBottomLine: false
  theme:
    activeBorderColor:
      - '#fabd2f'  # gruvbox yellow
      - bold
    inactiveBorderColor:
      - '#665c54'  # gruvbox gray
    searchingActiveBorderColor:
      - '#fe8019'  # gruvbox orange
      - bold
    optionsTextColor:
      - '#83a598'  # gruvbox blue
    selectedLineBgColor:
      - '#3c3836'  # gruvbox bg1
    selectedRangeBgColor:
      - '#504945'  # gruvbox bg2
    cherryPickedCommitBgColor:
      - '#689d6a'  # gruvbox aqua
    cherryPickedCommitFgColor:
      - '#282828'  # gruvbox bg
    unstagedChangesColor:
      - '#fb4934'  # gruvbox red
    defaultFgColor:
      - '#ebdbb2'  # gruvbox fg
  border: rounded
  nerdFontsVersion: '3'
